// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type Metadata struct {
	Key   string
	Value string
}

type Player struct {
	ID         int64
	InGameName sql.NullString
	IsOnline   bool
	IsBot      bool
}

type TokenStore struct {
	Token   []byte
	Expires time.Time
	Type    string
	UserID  int64
}

type User struct {
	ID       int64
	Name     sql.NullString
	PlayerID sql.NullInt64
	TgID     sql.NullInt64
}
