// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type TokenStore struct {
	Token   []byte
	Expires time.Time
	Type    string
	UserID  int64
}

type User struct {
	ID   int64
	Name sql.NullString
}
